DROP DATABASE IF EXISTS sample;
CREATE DATABASE sample DEFAULT CHARACTER SET utf8;

GRANT USAGE ON *.*
TO sample IDENTIFIED BY 'sample';
DROP USER sample;

GRANT SELECT, INSERT, UPDATE, DELETE ON sample.*
TO sample IDENTIFIED BY 'sample';
