DROP DATABASE IF EXISTS database_name;
CREATE DATABASE database_name DEFAULT CHARACTER SET utf8;

GRANT USAGE ON *.*
TO 'user' IDENTIFIED BY 'password';
DROP USER 'user';

GRANT SELECT, INSERT, UPDATE, DELETE ON database_name.*
TO 'user' IDENTIFIED BY 'password';
